### ISSUE TITLE
Download page is broken on the wiki

### ISSUE THREAD

**Issue by harre096** [Nicolas01/Highlightjs_Integration#1]
Nice extension!

I just wanted to let you know that I could only download the source code from Github.
The download link on your extention page points to https://www.mediawiki.org/wiki/Special:ExtensionDistributor/Highlightjs_Integration/HighlightjsIntegration, which doesn't appear to work.

Let me know if I can help as well,
Thanks!

**Comment by Nicolas01** [comment]
Thanks for your comment.
I don't know how to make work the page https://www.mediawiki.org/wiki/Special:ExtensionDistributor/Highlightjs_Integration  
I would be happy to receive help on this issue.
In the meantime, I will change the download link to GitHub repo.

**Comment by harre096** [comment]
I was poking around and I  don't how to work with the ExtentsionDistrbutor either. I think listing the github links on your page is helpful already, so I probably wouldn't worry about it. :)
Thanks for your work on this extension!
