### ISSUE TITLE
MW common pages highlight not working

### ISSUE THREAD

**Issue by keepersdungeon** [Nicolas01/Highlightjs_Integration#12]
Hello,
With the default stuff in the init.js nor the suggested code below worked to highlight the commone pages of mediawiki like common.css and common.js
`hljs.configure({
    cssSelector: 'pre.code2highlight, code.code2highlight, pre.mwcode'
});

hljs.highlightAll();`

The only one worked is this one from the syntaxhighlighJS v1.2 
`$(document).ready(function() {
    $('pre.code2highlight, code.code2highlight, pre.mw-code').each(function(i, block) {
        hljs.highlightBlock(block);
    });
});
`

**Comment by Nicolas01** [comment]
Version 2.2 should fix your issue.
If not, let me know.

**Comment by keepersdungeon** [comment]
Did not fix it

**Comment by Nicolas01** [comment]
To sum-up your issue:

- you have code highlight on mediawiki pages common.css and common.js
- you don't have code highlight on your pages with the following tags
```
<syntaxhighlight lang="js">
// some js code
</syntaxhighlight>
```
- with the version 2.2, if you edit the file `init.js` and edit the code as follows, then you have code highlight on your pages
```
// hljs.configure({
//     cssSelector: 'pre.code2highlight, code.code2highlight, pre.mwcode'
// });
// hljs.highlightAll();

$(document).ready(function() {
  $('pre.code2highlight, code.code2highlight, pre.mw-code').each(
    function(i, block) { hljs.highlightBlock(block); }
  );
}); 
```

Am I correct with those assumptions?
