### ISSUE TITLE
 SyntaxHighlight uses deprecated Sanitizer::validateAttributes syntax

### ISSUE THREAD

**Issue by RenHoekNL** [Nicolas01/Highlightjs_Integration#13]
On a page where I use SyntaxHighlight, once I click submit, I get a huge page with warnings, foremost:

Deprecated: Use of Sanitizer::validateAttributes with sequential array was deprecated in MediaWiki 1.35. [Called from HighlightjsIntegration::renderSyntaxhighlight in C:\wamp\www\wiki\extensions\Highlightjs_Integration-master\HighlightjsIntegration.class.php at line 42] in C:\wamp\www\wiki\includes\debug\MWDebug.php on line 381

I'm using Mediawiki 1.39.1 (lastest) with latest version of Highlightjs_Integration.

**Comment by Nicolas01** [comment]
Thanks for the feedback. I am going to publish a new version soon to fix it.

**Comment by Nicolas01** [comment]
Fixed in version 2.2

**Comment by RenHoekNL** [comment]
Thanks for the fix!
