### ISSUE TITLE
Extension not working in VisualEditor

### ISSUE THREAD

**Issue by SheepRock** [Nicolas01/Highlightjs_Integration#2]
When I try to edit a page using VisualEditor, nothing is shown in the code lines. Is there a way to make it work in VisualEditor like SyntaxHighlight_GeSHi does?

I'm using version 1.2 in xampp with MediaWiki 1.31.1, PHP 7.0.33.

**Comment by Nicolas01** [comment]
Sorry for the late answer.
It seems to be fixed in Mediawiki version 1.35.7
Here is the VisualEditor rendering of the following Mediawiki code:
```markdown
<syntaxhighlight lang='cs'>
var v = new Class(10, "xxx");
</syntaxhighlight>
```

![image](https://user-images.githubusercontent.com/2211631/185798278-6439e09d-fd00-41fb-93d7-5bd3ebbc1b39.png)
