### ISSUE TITLE
List Processing & Highlighting Breaks

### ISSUE THREAD

**Issue by jakeman95** [Nicolas01/Highlightjs_Integration#3]
When using this extension and attempting to use <SyntaxHighlight> within a numbered list and more than one line of code, like such:

```
# Step1
# Step 2 has some code: <SyntaxHighlight lang="bash">
Totally
some
bash lines
here
</SyntaxHighlight>
# Step 3
```

the output is butchered:
* The first line is highlighted
* The middle lines are in a separate pre block and not highlighted
* The last line is left out as as standard text
* The list numbering resets

It appears that there is a need to strip code if a parser is used.  I was able to modify the code using some slightly edited code from the native SyntaxHighlight_GeSHi module to fix this:

```
	if ($inline) {
		$htmlAttribs['style'] = 'display: inline;';
		$out = Html::rawElement('code', $htmlAttribs, $code);
		return $out;
	} else {
		if ( $parser ) {
			// Use 'nowiki' strip marker to prevent list processing (also known as doBlockLevels()).
			// However, leave the wrapping <div/> outside to prevent <p/>-wrapping.
			$marker = $parser::MARKER_PREFIX . '-syntaxhighlightinner-' .
				sprintf( '%08X', $parser->mMarkerIndex++ ) . $parser::MARKER_SUFFIX;
			$parser->getStripState()->addNoWiki( $marker, $code );
			$code = $marker;
		}
		$out = Html::rawElement('pre', $htmlAttribs, $code);
		return $out;
	}
```

Modifying the code as shown would then properly box in all the code in the numbered list and keep the list numbering intact.

Also, note really a bug or related, but more as a easy migration from the builtin tooling to this extension (since it doesn't work on Windows and this does), I also added the following to catch (enclose="none"):

```
		$inline = isset($param['inline']);
		if ($param['enclose'] == 'none') {
			$inline = true;
		}
```

**Comment by Nicolas01** [comment]
Fixed with your help @jakeman95 and @kuenzign in version 2.1
